nav:
  display_title: true
  fixed: false # fixed navigation bar
post_asset_folder: true
menu:
  Home: / || fas fa-home
  Archives: /archives/ || fas fa-archive
  Tags: /tags/ || fas fa-tags
  Categories: /categories/ || fas fa-folder-open
  List||fa fa-heartbeat:
    music: /music/ || fas fa-music
    photo: /Gallery/ || fas fa-images
    movie: /movies/ || fas fa-video

#头像
avatar:
  img: /image/3.png
  # effect: true # 头像会一直转，转的贼快，太鬼畜了

#顶部图
index_img: /image/5.jpg
default_top_img: /image/5.jpg
footer_bg: true




#运行时间



#本地搜索
# Local search
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # 如果没有查到内容相关内容显示


#背景特效
inject:
  head:
    - <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    - <link rel="stylesheet" href="/styles/main.css">
    - <link rel="stylesheet" href="/tags/tags.css">
    - <link rel="stylesheet" href="/styles/transparency.css">
  bottom:
    - <script src="/styles/fish.js"></script>

#动态彩带背景
canvas_fluttering_ribbon:
  enable: true
  mobile: false # false 手机端不显示 true 手机端显示



#鼠标
fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: true


hr_icon: # 水平分隔线图标设置，带个小剪刀图标
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon-top:

# 主页subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 200 # type speed in milliseconds
  backSpeed: 800 # backspacing speed in milliseconds
  # loop (循环打字)
  loop: true
  # source 调用三方服务
  # source: false 开关调用
  # subtitle 会先显示 source , 再显示 sub 的內容
  source: true
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:
    - 我们走过了许多弯路，但错误常常是正确的先导

#加载动画
preloader:
  enable: true
  source: 1 #可选值1=fullpage或2=progress bar，可查看https://codebyzach.github.io/pace/
  pace_css_url:

#自定义颜色
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
  scrollbar_color: "#49b1f5"

mask: # 为 header 或 footer 添加黑色半透遮罩
  header: false
  footer: true

favicon: /image/6.jpg

#代码块
highlight_theme: mac  #  darker / pale night / light / ocean / mac / mac light / false 代码主题
highlight_copy: true # 复制按钮
highlight_lang: false # 是否显示代码语言
highlight_shrink: false # true: 代码块默认不展开 / false: 代码块默认展开 | none: 展开并隐藏折叠按钮
highlight_height_limit: false # unit: px
code_word_wrap: true #代码自动换行，关闭滚动条

#图片懒加载
lazy load:
  enable: true
  loadingImg: /img/loading.gif

#大图查看
medium_zoom: false
fancybox: true

# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖动特效)
  mobile: true

# wordcount (字數統計)
word count:
  enable: true
  post_word count: true
  min2read: true
  total_word count: true
