nav:
  display_title: true
  fixed: false # fixed navigation bar
post_asset_folder: true
menu:
  Home: / || fas fa-home
  Archives: /archives/ || fas fa-archive
  Tags: /tags/ || fas fa-tags
  Categories: /categories/ || fas fa-folder-open
  Link: /link/ || fas fa-link

#头像
avatar:
  img: /image/3.png
  # effect: true # 头像会一直转，转的贼快，太鬼畜了

#顶部图
index_img: /image/5.jpg
footer_bg: true




#运行时间



highlight_theme: false
highlight_shrink: false
highlight_fullpage: true

#背景特效
inject:
  head:
    - <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    - <link rel="stylesheet" href="/styles/main.css">
    - <link rel="stylesheet" href="/tags/tags.css">
    - <link rel="stylesheet" href="/styles/transparency.css">
    - <link rel="stylesheet" href="/styles/custom.css">
  bottom:
    - <script src="/styles/fish.js"></script>

#动态彩带背景
canvas_fluttering_ribbon:
  enable: true
  mobile: false # false 手机端不显示 true 手机端显示



#鼠标
fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: true


hr_icon: # 水平分隔线图标设置，带个小剪刀图标
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon-top:

# 主页subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 200 # type speed in milliseconds
  backSpeed: 800 # backspacing speed in milliseconds
  # loop (循环打字)
  loop: true
  # source 调用三方服务
  # source: false 开关调用
  # subtitle 会先显示 source , 再显示 sub 的內容
  source: true
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:
    - 我们走过了许多弯路，但错误常常是正确的先导

#加载动画
preloader:
  enable: true
  source: 1 #可选值1=fullpage或2=progress bar，可查看https://codebyzach.github.io/pace/
  pace_css_url:

#自定义颜色
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
  scrollbar_color: "#49b1f5"

mask: # 为 header 或 footer 添加黑色半透遮罩
  header: false
  footer: true

favicon: /image/6.jpg

code_blocks:
  # Code block theme: darker / pale night / light / ocean / false
  theme: ocean
  macStyle: true
  # Code block height limit (unit: px)
  height_limit: 200
  word_wrap: false

  # Toolbar
  copy: true
  language: true
  # true: shrink the code blocks | false: expand the code blocks | none: expand code blocks and hide the button
  shrink: false
  fullpage: false


#图片懒加载
lazy load:
  enable: true
  loadingImg: /img/loading.gif

#大图查看
medium_zoom: false
fancybox: true

# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖动特效)
  mobile: true

# 需要安裝 hexo-wordcount 插件
wordcount:
  # 是否啟用字數統計
  enable: true
  # 在文章元信息中顯示字數統計
  post_wordcount: true
  # 在文章元信息中顯示閲讀時間
  min2read: true
  # 在側邊欄網站信息中顯示總字數
  total_wordcount: true


# A simple 404 page
error_404:
  enable: true
  subtitle: '页面没有找到'
  background:

# 文章元數據設置
post_meta:
  # 主頁頁面
  page:
    # 日期類型: created / updated / both
    date_type: created
    # 日期格式: date / relative
    date_format: date
    # 是否顯示分類
    categories: true
    # 是否顯示標籤
    tags: false
    # 是否顯示文字標籤
    label: true
  # 文章頁面
  post:
    # 元數據位置: left / center
    position: left
    # 日期類型: created / updated / both
    date_type: both
    # 日期格式: date / relative
    date_format: date
    # 是否顯示分類
    categories: true
    # 是否顯示標籤
    tags: true
    # 是否顯示文字標籤
    label: true

# 相關文章
related_post:
  # 是否顯示相關文章
  enable: true
  # 顯示的文章數量
  limit: 6
  # 選擇: created / updated
  date_type: created

# 選擇: 1 / 2 / false
# 1: “下一篇文章”將鏈接到舊文章
# 2: “下一篇文章”將鏈接到新文章
# false: 禁用分頁
post_pagination: 1

# 顯示文章過期通知
noticeOutdate:
  # 是否啟用過期通知
  enable: false
  # 樣式: simple / flat
  style: flat
  # 多少天后顯示通知
  limit_day: 365
  # 位置: top / bottom
  position: top
  message_prev: 已经过了
  message_next: 天自上次更新，文章內容可能已过时。

# 暗黑模式設置
darkmode:
  # 是否啟用暗黑模式
  enable: true
  # 切換暗黑/明亮模式的按鈕
  button: true
  # 是否自動切換暗黑/明亮模式
  # autoChangeMode: 1  跟隨系統設置，如果系統不支持暗黑模式，則在晚上 6 點到早上 6 點之間切換暗黑模式
  # autoChangeMode: 2  在晚上 6 點到早上 6 點之間切換暗黑模式
  # autoChangeMode: false  不自動切換
  autoChangeMode: false
  # 設置明亮模式時間，值在 0 到 24 之間。如果未設置，默認值為 6 和 18
  start:
  end:


# 本地搜索
local_search:
  # 頁面加載時預加載搜索數據
  preload: false
  # 每篇文章顯示的頂部 n 個搜索結果，設置為 -1 顯示所有結果
  top_n_per_article: 1
  # 將 HTML 字符串反轉義為可讀內容
  unescape: false
  CDN:

# 目录
toc:
  post: true
  page: false
  number: true
  expand: false
  # Only for post
  style_simple: false
  scroll_percent: true

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/Abxery/Abxery.github.io
  card_tags:
    enable: true
    # If set 0 will show all
    limit: 40
    color: true
    # Order of tags, random/name/length
    orderby: name
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: 1
    sort_order:


runtimeshow:
  enable: true
  publish_date: 2024/10/20

cover:
  index_enable: true #  是否展示文章封面
  aside_enable: true
  archives_enable: true
  position: both
  default_cover: /image/5.jpg
  # 封面展示的位置 left/right/both
  # 当没有设置cover时，默认展示的文章封面

math:
  # Choose: mathjax, katex
  # Leave it empty if you don't need math
  use: mathjax
  per_page: true
  hide_scrollbar: false

  mathjax:
    # Enable the contextual menu
    enableMenu: true
    # Choose: all / ams / none, This controls whether equations are numbered and how
    tags: true
    enable: true
    per_page: true

  katex:
    # Enable the copy KaTeX formula
    copy_tex: false

#页面顶图配置
#category_per_img和tag_per_img，可配置多张，每次会随机取一张
#format:
# - category name: xxxxx
disable_top_img: false
default_top_img: /image/5.jpg
tag_img: https://s2.loli.net/2024/10/29/AzfC2VW7I9KcX6a.jpg
tag_per_img:
  - https://s2.loli.net/2024/10/29/y9XSQrcpHAPwTsY.jpg
  - https://s2.loli.net/2024/10/29/VTqt6jpIBGdZohW.jpg
category_img: https://s2.loli.net/2024/10/29/PhXBLls2bwycZVe.jpg
category_per_img:
  - https://s2.loli.net/2024/10/29/bve5UXFLYqI4lBT.jpg
  - https://s2.loli.net/2024/10/29/Z5mIMrgq8vH1E6N.jpg